language: cpp
os:
  - linux
  - osx

sudo: false

env:
  matrix:
   - DBGTOOLS_CONFIG=debug
   - DBGTOOLS_CONFIG=release

compiler:
  - gcc
  - clang

install:
  - git clone https://github.com/matricks/bam.git
  - cd bam
  - ./make_unix.sh
  - cd ..

script:
  - bam/bam compiler=$CC config=$DBGTOOLS_CONFIG
  - local/$DBGTOOLS_CONFIG/linux_x86_64/test_assert
  - local/$DBGTOOLS_CONFIG/linux_x86_64/test_callstack
  - local/$DBGTOOLS_CONFIG/linux_x86_64/test_callstack_cpp
